### ISSUE TITLE
Cannot login after installation

### ISSUE THREAD

**Issue by clicit** [YunoHost-Apps/documize_ynh#7]
Installation worked without any issues, but when now trying to login nothing happens in the UI. 
When loading the authentication page loading the manifest.json file is blocked by CORS.
Submitting a login request then results in a HTTP 400 error.

<img width="650" alt="image" src="https://user-images.githubusercontent.com/26301562/212305104-fcfe806d-05b6-4a8a-b896-d7e5bf9491a3.png">

Documize version installed: 5.4.2~ynh1
YunoHost 11.0.10.2 (on VPS)

**Comment by davidszerman** [comment]
Hi

Same issue for me

**Comment by ericgaspar** [comment]
Can we get proper logs? Same issue is not enough
